# Generated by Django 4.0.4 on 2022-05-19 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 19, 21, 32, 37, 209640), verbose_name='fecha de registro'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 19, 21, 32, 37, 211639)),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 19, 21, 32, 37, 210639)),
        ),
    ]
